-- ${ctx.flywayDescription}
-- Generated by oa-generator
<#list ctx.allEntities as entity>
CREATE TABLE IF NOT EXISTS ${entity.tableName} (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
<#list entity.fields as f>
    ${f.column} ${f.sqlType}<#if !f.nullable> NOT NULL</#if><#if f.defaultValue??> DEFAULT ${f.defaultValue}</#if><#if f.comment??> COMMENT '${f.comment}'</#if>,
</#list>
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted     TINYINT      NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='${entity.comment!''}';
<#if entity.indexes?? && entity.indexes?size gt 0>

<#list entity.indexes as idx>
CREATE <#if idx.unique>UNIQUE </#if>INDEX ${idx.name} ON ${entity.tableName} (<#list idx.columns as c>${c}<#if c_has_next>, </#if></#list>);
</#list>
</#if>

</#list>
