-- V13: Align approval tables with BaseEntity fields used by MyBatis-Plus.

ALTER TABLE biz_approval_instance
    ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;

ALTER TABLE biz_approval_task
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;

ALTER TABLE biz_approval_cc
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
