-- leave_module
-- Generated by oa-generator
CREATE TABLE IF NOT EXISTS biz_leave_request (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL COMMENT '申请标题',
    leave_type TINYINT NOT NULL COMMENT '请假类型',
    start_time DATETIME NOT NULL COMMENT '开始时间',
    end_time DATETIME NOT NULL COMMENT '结束时间',
    reason TEXT COMMENT '请假原因',
    applicant_user_id BIGINT NOT NULL COMMENT '申请人ID',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态',
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted     TINYINT      NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='请假申请';

CREATE INDEX idx_applicant ON biz_leave_request (applicant_user_id);
CREATE INDEX idx_status ON biz_leave_request (status);

